
import argparse
import json
from collections import Counter
from datetime import datetime
from pathlib import Path


def generate_report(input_json, output_md):
    input_path = Path(input_json)
    output_path = Path(output_md)

    if not input_path.is_file():
        raise FileNotFoundError(f"Analysis JSON not found: {input_path}")

    data = json.loads(input_path.read_text(encoding="utf-8"))
    packets = data.get("packets", [])
    connections = data.get("connections", [])

    protocols = Counter(data.get("protocol_counts", {}))
    timestamps = [
        packet["timestamp"]
        for packet in packets
        if packet.get("timestamp")
    ]

    lines = [
        "# Network Forensic Analysis Report",
        "",
        f"**Capture file:** {data.get('capture_file', 'Unknown')}",
        f"**Packets analyzed:** {data.get('total_packets', len(packets))}",
        "",
        "## Protocol Summary",
        "",
        "| Protocol | Packet Count |",
        "|---|---:|",
    ]

    for protocol, count in protocols.items():
        lines.append(f"| {protocol} | {count} |")

    lines.extend([
        "",
        "## Connection Summary",
        "",
        "| Source | Destination | Protocol | Packets |",
        "|---|---|---|---:|",
    ])

    for connection in connections:
        source = f"{connection.get('src_ip')}:{connection.get('src_port') or '-'}"
        destination = f"{connection.get('dst_ip')}:{connection.get('dst_port') or '-'}"
        protocol = connection.get("protocol", "Unknown")
        count = connection.get("packet_count", 0)

        lines.append(
            f"| {source} | {destination} | {protocol} | {count} |"
        )

    lines.extend(["", "## Packet Timeline", ""])

    for packet in packets:
        lines.append(
            "- "
            f"`{packet.get('timestamp', 'Unknown time')}` — "
            f"{packet.get('src_ip') or 'Unknown'} → "
            f"{packet.get('dst_ip') or 'Unknown'}; "
            f"{packet.get('protocol', 'Unknown')}; "
            f"{packet.get('packet_length', 0)} bytes"
        )

    lines.extend([
        "",
        "## Observations and Limitations",
        "",
        f"- First recorded packet: {min(timestamps) if timestamps else 'Unavailable'}",
        f"- Last recorded packet: {max(timestamps) if timestamps else 'Unavailable'}",
        "- This report describes observed packet metadata.",
        "- Connection patterns alone do not establish malicious activity.",
        "- No ransomware detection verdict is produced by this report.",
        "",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")

    return output_path


def main():
    parser = argparse.ArgumentParser(
        description="Generate a Markdown report from PCAP analyzer JSON."
    )
    parser.add_argument(
        "--input",
        default="person3/outputs/pcap_analysis.json",
        help="Input JSON generated by pcap_analyzer.py",
    )
    parser.add_argument(
        "--output",
        default="person3/outputs/forensic_report.md",
        help="Output Markdown report",
    )
    args = parser.parse_args()

    try:
        report_path = generate_report(args.input, args.output)
    except (OSError, ValueError, TypeError) as exc:
        parser.error(str(exc))

    print(f"Forensic report saved to: {report_path}")


if __name__ == "__main__":
    main()